version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: sims-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=simsdb;User=sa;Password=SomePass123!;TrustServerCertificate=True;"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sims-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SomePass123!"
    volumes:
      - sims-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: sims-redis
    ports:
      - "6379:6379"   # optional: remove if you don't want host access
    volumes:
      - redis-data:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf   # optional custom config
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      Redis__Connection: "redis:6379"


volumes:
  sims-data:
  redis-data:
